@startuml
package タスク集約 {
    object タスク {
        タスクID
        件名
    }
    object 期限 {
    }
    object カテゴリ {
        カテゴリID
    }
    object 進捗ステータス {
        ステータスID
    }
    object ラベル {
        ラベルID
    }
}

package ユーザー集約 {
    object ユーザー {
    }
}


@enduml