@startuml
package タスク集約 {
    class タスク << (A,#f6d53d) AggregateRoot>>{
        タスクID
        カテゴリID
        件名
        担当者ID
        期限
        ステータスID
    }
    note right
        ・タスクIDはUUID
        ・登録時の初期ステータスは未着手
    end note
    class 期限 << (V,#f6d53d) ValueObject>> {
        期限
    }
    note left
        ・過去日付は設定できない
    end note
    class タスク_ラベル << (E,#f6d53d) Entity>> {
        タスクID
        ラベルID
    }
}

package カテゴリ集約 {
    object カテゴリ {
        カテゴリID
    }
}

package 進捗ステータス集約 {
    object 進捗ステータス {
        ステータスID
    }
}

package ラベル集約 {
    object ラベル {
        ラベルID
    }
}

package ユーザー集約 {
    object ユーザー {
        ユーザID
    }
}

ユーザー <-- タスク
進捗ステータス <-- タスク
カテゴリ <-- タスク
タスク "1" *-- "0..n" タスク_ラベル
ラベル <-- タスク_ラベル
@enduml